/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardRutinaRouteImport } from './routes/_authenticated/dashboard.rutina'
import { Route as AuthenticatedDashboardPerfilRouteImport } from './routes/_authenticated/dashboard.perfil'
import { Route as AuthenticatedDashboardFormularioRouteImport } from './routes/_authenticated/dashboard.formulario'
import { Route as AuthenticatedDashboardAlimentacionRouteImport } from './routes/_authenticated/dashboard.alimentacion'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRutinaRoute =
  AuthenticatedDashboardRutinaRouteImport.update({
    id: '/rutina',
    path: '/rutina',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPerfilRoute =
  AuthenticatedDashboardPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFormularioRoute =
  AuthenticatedDashboardFormularioRouteImport.update({
    id: '/formulario',
    path: '/formulario',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAlimentacionRoute =
  AuthenticatedDashboardAlimentacionRouteImport.update({
    id: '/alimentacion',
    path: '/alimentacion',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/alimentacion': typeof AuthenticatedDashboardAlimentacionRoute
  '/dashboard/formulario': typeof AuthenticatedDashboardFormularioRoute
  '/dashboard/perfil': typeof AuthenticatedDashboardPerfilRoute
  '/dashboard/rutina': typeof AuthenticatedDashboardRutinaRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/alimentacion': typeof AuthenticatedDashboardAlimentacionRoute
  '/dashboard/formulario': typeof AuthenticatedDashboardFormularioRoute
  '/dashboard/perfil': typeof AuthenticatedDashboardPerfilRoute
  '/dashboard/rutina': typeof AuthenticatedDashboardRutinaRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/alimentacion': typeof AuthenticatedDashboardAlimentacionRoute
  '/_authenticated/dashboard/formulario': typeof AuthenticatedDashboardFormularioRoute
  '/_authenticated/dashboard/perfil': typeof AuthenticatedDashboardPerfilRoute
  '/_authenticated/dashboard/rutina': typeof AuthenticatedDashboardRutinaRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/alimentacion'
    | '/dashboard/formulario'
    | '/dashboard/perfil'
    | '/dashboard/rutina'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/alimentacion'
    | '/dashboard/formulario'
    | '/dashboard/perfil'
    | '/dashboard/rutina'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/alimentacion'
    | '/_authenticated/dashboard/formulario'
    | '/_authenticated/dashboard/perfil'
    | '/_authenticated/dashboard/rutina'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/rutina': {
      id: '/_authenticated/dashboard/rutina'
      path: '/rutina'
      fullPath: '/dashboard/rutina'
      preLoaderRoute: typeof AuthenticatedDashboardRutinaRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/perfil': {
      id: '/_authenticated/dashboard/perfil'
      path: '/perfil'
      fullPath: '/dashboard/perfil'
      preLoaderRoute: typeof AuthenticatedDashboardPerfilRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/formulario': {
      id: '/_authenticated/dashboard/formulario'
      path: '/formulario'
      fullPath: '/dashboard/formulario'
      preLoaderRoute: typeof AuthenticatedDashboardFormularioRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/alimentacion': {
      id: '/_authenticated/dashboard/alimentacion'
      path: '/alimentacion'
      fullPath: '/dashboard/alimentacion'
      preLoaderRoute: typeof AuthenticatedDashboardAlimentacionRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAlimentacionRoute: typeof AuthenticatedDashboardAlimentacionRoute
  AuthenticatedDashboardFormularioRoute: typeof AuthenticatedDashboardFormularioRoute
  AuthenticatedDashboardPerfilRoute: typeof AuthenticatedDashboardPerfilRoute
  AuthenticatedDashboardRutinaRoute: typeof AuthenticatedDashboardRutinaRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAlimentacionRoute:
      AuthenticatedDashboardAlimentacionRoute,
    AuthenticatedDashboardFormularioRoute:
      AuthenticatedDashboardFormularioRoute,
    AuthenticatedDashboardPerfilRoute: AuthenticatedDashboardPerfilRoute,
    AuthenticatedDashboardRutinaRoute: AuthenticatedDashboardRutinaRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
